# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bcbf9dfb209d9ceb441b2a8acb6a7a52"
name = "Block Country"
handle = "block-country-2"
application_url = "https://wu-deputy-chocolate-belief.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = ["https://wu-deputy-chocolate-belief.trycloudflare.com/auth/callback", "https://wu-deputy-chocolate-belief.trycloudflare.com/auth/shopify/callback", "https://wu-deputy-chocolate-belief.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://wu-deputy-chocolate-belief.trycloudflare.com/data/info"
subpath = "proxy-1"
prefix = "apps"


[pos]
embedded = false
