# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06727b2113c9cc212b445f710bcc3aff"
name = "Block Country"
handle = "block-country-1"
application_url = "https://block-country.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://block-country.onrender.com/auth/callback",
  "https://block-country.onrender.com/auth/shopify/callback",
  "https://block-country.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://block-country.onrender.com/data/info"
subpath = "proxy-1"
prefix = "apps"

[pos]
embedded = false
