# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7336a0b90ddf9a11935b69c5bd69a4c0"
name = "Block Country"
handle = "block-country-1"
application_url = "https://block-country.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true 

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = ["https://block-country.onrender.com/api/auth/callback", "https://block-country.onrender.com/auth/shopify/callback", "https://block-country.onrender.com/auth/callback"]

[app_proxy]
url = "https://block-country.onrender.com/data/info"
subpath = "proxy"
prefix = "apps"

[pos]   
embedded = false
